# Site Configuration
baseurl: "" # Subpath to website
url: "https://hmendozap.github.io"
# THEME-SPECIFIC CONFIGURATION
theme_settings:
    title: GP Sample Extraordinare
    avatar: pp.jpg
    gravatar: # Email MD5 hash
    description: "A website with blog posts and pages about a nicaraguan in search for a Master's" # used by search engines

    # Header and footer text
    header_text: >
        <p> Coffee, beer, bacon, sports and Gaussian Processes... </p>
    header_text_feature_image:
    footer_text: >
        Copyright 2015. Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

    # Icons
    rss: false
    email_address: # Full email address, e.g. "sam@example.com"
    behance:
    bitbucket:
    dribbble:
    facebook:
    flickr:
    github: "hmendozap/"
    google_plus:
    instagram:
    linkedin:  # Full URL
    pinterest:
    reddit:
    soundcloud:
    stack_exchange:  # Full URL
    steam:
    tumblr:
    twitter: "nicamendoza"
    wordpress:
    youtube:

    # Scripts
    google_analytics: # Tracking ID, e.g. "UA-000000-01"
    disqus_shortname: "GP-Sample"
    muut_community_name: # From muut.com settings, e.g. "muttcommunityname"    katex: true # Enable if using math markup
    # Localization strings
    str_follow_on: "Aquí estoy en"
    str_rss_follow: "Follow RSS feed"
    str_email: "Deja un mensaje"
    str_next: "Siguiente"
    str_prev: "Anterior"
    str_continue_reading: "Enterate..."

    # Colours, typography and padding
    # Open the "_sass > base" folder, and open "_variables.scss"
    google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

    # Post navigation
    post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"



# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
